[package]
name = "etk-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "ETK regulator/auditor CLI — offline verifier"

[[bin]]
name = "etk"
path = "src/main.rs"

[build-dependencies]

[dependencies]
etk-core = { path = "../etk-core" }
etk-types = { path = "../etk-types" }
ed25519-dalek = "2.0"
